services:
  - type: web
    name: vehiculos-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vehiculos-db
          property: connectionString

databases:
  - name: vehiculos-db
    plan: free
